apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      name: "server"
      labels:
        app: "server"
    spec:
      serviceAccount: server
      containers:
        - name: server
          image: "castmoon/hello-world-go"

          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
