apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  # filter correct pods
  selector:
    app: goserver
  type: LoadBalancer
  ports:
    - name: goserver-service
      # this is the service port
      port: 8000
      # this is the container port
      targetPort: 80
      protocol: TCP
